# Generated by Django 6.0.5 on 2026-05-25 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Procurement & Fuel Export (CSV)'), ('UTILITY', 'Utility Portal Monthly Export (CSV)'), ('CONCUR', 'Concur Corporate Travel API Sync (JSON)')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch_reference', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='emissions.organization')),
            ],
            options={
                'verbose_name_plural': 'Data Batches',
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 (Direct Emissions)'), ('2', 'Scope 2 (Indirect - Purchased Electricity)'), ('3', 'Scope 3 (Value Chain / Travel / Procurement)')], max_length=1)),
                ('category', models.CharField(max_length=100)),
                ('source_row_index', models.IntegerField(help_text='Line or object index from the original dataset')),
                ('raw_data_payload', models.JSONField(help_text='Immutable snapshot of the original input data structure')),
                ('original_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('original_unit', models.CharField(max_length=30)),
                ('normalized_value_kwh', models.DecimalField(blank=True, decimal_places=4, help_text='Normalized energy equivalent if applicable', max_digits=15, null=True)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated greenhouse gas impact', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Analyst Review'), ('SUSPICIOUS', 'Flagged Suspicious'), ('APPROVED', 'Approved & Locked for Audit')], default='PENDING', max_length=15)),
                ('validation_flags', models.JSONField(blank=True, default=list, help_text='List of automation warning strings if data looks odd')),
                ('is_locked', models.BooleanField(default=False, help_text='Once true, records are read-only and sealed for auditors')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.databatch')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_field', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Optional correction context provided by the analyst')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
